### ISSUE TITLE
Too many calls to the Trello API

### ISSUE THREAD

**Issue by Walrusse** [Wolters-Kluwer-Canada/supermetaboard#1]
Right now, everything is brought back by the dictionnary. 

We should probably only load what is selected in the filters instead of everything.
![capture d ecran 2015-02-27 a 16 54 36](https://cloud.githubusercontent.com/assets/3384713/6421930/58e6602e-bea1-11e4-9ef6-699ad7ec2d1d.png)

Failed to load resource: the server responded with a status of 429 (Too Many Requests)

**Comment by yonguelink** [comment]
Okay, I was starting to run in something similar: How to append all the user image to the proper card? Nothing would be better than simply appending them to the proper div's ID during their creation (so, in the loading time between the time the we click on the menu and we show something) -- Probably will need to add some "pending" part, so we tell the user we're actually working on something.

**Comment by yonguelink** [comment]
This has been updated. The global dictionary is no more. 

How it goes now:

1. Page load 
   * Loads the menu - Loops on boards of the users and on the lists of each board
2. Menu click
   * Board menu click -> Loads the lists of the selected board
   * State menu click
      * Loops on all the boards of the users to check if there's a list with the selected nam
      * If there is a list with the name, then we load its card and write it to the content div

**Comment by Walrusse** [comment]
commit e613b51e241c9c4f798d0ad36641fac59636d26b solves this.
